name: Build and Release Floatkit

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v1.0.0

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1

      - name: Configure
        run: cmake -S Floatkit -B build

      - name: Build
        run: cmake --build build --config Release

      - name: Upload executable artifact
        uses: actions/upload-artifact@v4
        with:
          name: Floatkit.exe
          path: build/bin/Floatkit.exe

  release:
    runs-on: windows-latest
    needs: build

    steps:
      - name: Download executable
        uses: actions/download-artifact@v4
        with:
          name: Floatkit.exe
          path: .

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: Floatkit.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}